---
galaxy_info:
  role_name: rudder_server
  namespace: rudder
  author: Rudder
  description: Ansible role to install Rudder Server
  company: Rudder
  license: GPLv3
  min_ansible_version: 2.9

  galaxy_tags:
  - rudder
  - automation
  - compliance
  - audit

  platforms:
    - name: Ubuntu
      versions:
        - 10.04-LTS
        - 12.04-LTS
        - 14.04-LTS
        - 16.04-LTS
        - 18.04-LTS
        - 20.04-LTS

    - name: Debian
      versions:
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11

    - name: SLES
      versions:
         - 10-SP3
         - 11

    - name: RHEL
      versions:
         - 3
         - 5
         - 6
         - 7
         - 8

dependencies:
  - role: rudder_repository
    vars:
      repository: "{{ rudder_repository }}"
      rudder_version: "{{ server_version }}"
      repository_url: "{{ rudder_repository_url }}"
      rudder_update_cache: "{{ update_cache }}"
      repository_username: "{{ rudder_repository_username }}"
      repository_password: "{{ rudder_repository_password }}"
      rudder_apt_key_url: "{{ apt_key_url }}"
      rudder_rpm_key_url: "{{ rpm_key_url }}"
