name: Python unit tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r ci/requirements.txt -r utils/python/requirements/base-requirements.txt -r utils/python/requirements/roles-requirements.txt
          python -m unittest discover -s tests/unit/plugins/modules

      - uses: dtolnay/rust-toolchain@1.91.0
      - name: Run typos check
        run: |
          cargo install -f typos-cli --version=1.39.2
          typos

      - uses: actions/checkout@v4
        with:
          path: ansible_collections/rudder/rudder
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install ansible-core
      - name: Run sanity tests
        working-directory: ansible_collections/rudder/rudder
        run: ansible-test sanity
